[package]
name = "pairing"

# Remember to change version string in README.md.
version = "0.14.3"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <jack@z.cash>",
]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/ebfull/pairing"
repository = "https://github.com/ebfull/pairing"

[lib]
# crate-type = ["staticlib"]



[dependencies]
rand = "0.4"
byteorder = "1"
ff = { version = "0.4", features = ["derive"] }
sha2 = "0.8"




[features]
unstable-features = ["expose-arith"]
expose-arith = []
default = []
